import * as Joi from 'joi';

export const shutterstockAPIQuerySchema = Joi.object({
  added_date: Joi.string().pattern(/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/),
  added_date_end: Joi.string().pattern(/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/),
  added_date_start: Joi.string().pattern(/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/),
  aspect_ratio: Joi.number(),
  aspect_ratio_max: Joi.number(),
  aspect_ratio_min: Joi.number(),
  category: Joi.string(),
  color: Joi.string(),
  contributor: Joi.array().items(Joi.string()),
  contributor_county: Joi.array().items(Joi.string().pattern(/^[a-zA-Z]{2}$|^NOT [a-zA-Z]{2}$/)),
  fields: Joi.string(),
  height_from: Joi.number(),
  height_to: Joi.number(),
  image_type: Joi.string().pattern(/^photo$|^illustration$|^vector$/),
  keyword_safe_search: Joi.boolean(),
  language: Joi.string(),
  license: Joi.array().items(Joi.string().pattern(/^commercial$|^editorial$|^enhanced$/)),
  model: Joi.array().items(Joi.string()),
  orientation: Joi.string().pattern(/^horizontal$|^vertical$/),
  page: Joi.number(),
  people_age: Joi.string().pattern(/^infants$|^children$|^teenagers$|^20s$|^30s$|^40s$|^50s$|^60s$|^older$/),
  people_ethnicity: Joi.array().items(Joi.string()),
  people_gender: Joi.string().pattern(/^male$|^female$|^both$/),
  people_model_released: Joi.boolean(),
  people_number: Joi.number(),
  per_page: Joi.number(),
  query: Joi.string(),
  region: Joi.string(),
  safe: Joi.boolean(),
  sort: Joi.string().pattern(/^newest$|^popular$|^relevance$|^random$/),
  spellcheck: Joi.boolean(),
  view: Joi.string().pattern(/^minimal$|^full$/),
  width_from: Joi.number(),
  width_to: Joi.number(),
  height: Joi.number(),
  width: Joi.number(),
});
